### PR TITLE
btt hdmi5 mount for clicky clacky door with door buffer

### PR DESCRIPTION
**Pull request by MRSalguod**
Added a user mod btt hdmi5 mount for clicky clacky door for use with the dreaftshift door buffer v2.

### CODE REVIEW

**Comment by TheSin-** [comment]
You need to link and credit to original design I. The readme pleaee

**Comment by MRSalguod** [comment]
Ok added links/credit.

**Comment by TheSin-** [comment]
Sorry I didn’t notice earlier but the usermod dir needs to be your github username so it all links, once that’s done I’ll accept it, thanks for the contribution

**Comment by MRSalguod** [comment]
Ok, I changed my username.

**Pull request merged**
